language: python
python:
  - "2.7"
sudo: required
install:
    - make devinstall
script: make test
notifications:
    irc:
        channels:
            - "irc.freenode.net#ideasbox"
        on_success: change
        on_failure: always
    email: false
