language: python
python:
  - "2.7"
before_install:
    - pip install git+https://github.com/Erf-/wifi.git@connection-status#egg=wifi
sudo: required
install:
    - sudo apt-get install wireless-tools
    - make devinstall
script: make test
notifications:
    irc:
        channels:
            - "irc.freenode.net#ideasbox"
        on_success: change
        on_failure: always
    email: false
